version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8
  INSTALL_NODE_VERSION: 14

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ${WATCH}:/watch

services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "fibgen-development"
    depends_on:
      - "db"
    user: "${UID}:${GID}" 
    ports:
      - "5000:5000"
      - "2992:2992"
    <<: *default_volumes

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "fibgen-production"
    depends_on:
      - "db"  
    user: "${UID}:${GID}" 
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    user: "${UID}:${GID}" 
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "fibgen-manage"
    depends_on:
      - "db"  
    stdin_open: true
    tty: true
    <<: *default_volumes

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  node-modules:
  postgres_data: